name: full_load
description: A trucking dispatch and accounting app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1


  # File & Document Handling
  file_picker: ^10.3.1
  path_provider: ^2.1.2
  path: ^1.9.1
  url_launcher: ^6.3.2
  open_file: ^3.3.2
  archive: ^4.0.7
  share_plus: ^11.0.0

  # PDF & Printing
  pdf: ^3.10.6
  printing: ^5.12.0
  flutter_pdfview: ^1.3.2

  # Image Viewer
  photo_view: ^0.15.0

  # UI & State Management
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.5.1
  provider: ^6.1.2
  flutter_slidable: ^4.0.0
  intl: ^0.20.2

  # Geolocation & Maps
  google_maps_flutter: ^2.5.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # HTTP APIs
  http: ^1.2.1
  dio: ^5.4.2+1

  # Charts (for dashboards and reports)
  fl_chart: ^1.0.0

  # Windows Desktop shortcut
  process_run: ^1.2.4

  # CSV Export
  csv: ^6.0.0
  firebase_storage: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
