name: full_load
description: Full Load dispatch & accounting app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  http: ^1.2.2
  url_launcher: ^6.3.0

  # ---- Firebase 4.x family (keep these aligned) ----
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  # ---- App Check (compatible with firebase_core 4.x) ----
  firebase_app_check: ^0.4.0

  # ---- Auth UI ----
  firebase_ui_auth: ^3.0.0

  # ---- Files / preview / printing ----
  image_picker: ^1.2.0
  file_picker: ^10.3.1
  archive: ^3.6.1
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  share_plus: ^10.0.2

  printing: ^5.13.0
  pdf: ^3.11.0
  open_filex: ^4.5.0
  webview_flutter: ^4.8.0
  mime: ^1.0.5
  # pdfrx: ^1.6.9   # optional

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

