// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9SCZbuim1CYB22jR45TLrR20KiyY3HUw',
    appId: '1:1081293548287:web:e74d9840a384935e823aca',
    messagingSenderId: '1081293548287',
    projectId: 'johnny-app-93141',
    authDomain: 'johnny-app-93141.firebaseapp.com',
    storageBucket: 'johnny-app-93141.firebasestorage.app',
    measurementId: 'G-HZ68WJD5J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0aFYnRb8n6YXNVAwwdLlVVKWnKKzYg2c',
    appId: '1:1081293548287:android:c02893f6f67eb806823aca',
    messagingSenderId: '1081293548287',
    projectId: 'johnny-app-93141',
    storageBucket: 'johnny-app-93141.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxDjNEWlvZndFRYLLJF1m5FBVp01L7SnU',
    appId: '1:1081293548287:ios:3bc7d4120a6f516c823aca',
    messagingSenderId: '1081293548287',
    projectId: 'johnny-app-93141',
    storageBucket: 'johnny-app-93141.firebasestorage.app',
    iosBundleId: 'com.example.johnnyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxDjNEWlvZndFRYLLJF1m5FBVp01L7SnU',
    appId: '1:1081293548287:ios:3bc7d4120a6f516c823aca',
    messagingSenderId: '1081293548287',
    projectId: 'johnny-app-93141',
    storageBucket: 'johnny-app-93141.firebasestorage.app',
    iosBundleId: 'com.example.johnnyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9SCZbuim1CYB22jR45TLrR20KiyY3HUw',
    appId: '1:1081293548287:web:3a68544a49e065ff823aca',
    messagingSenderId: '1081293548287',
    projectId: 'johnny-app-93141',
    authDomain: 'johnny-app-93141.firebaseapp.com',
    storageBucket: 'johnny-app-93141.firebasestorage.app',
    measurementId: 'G-7RBMZ2JS8K',
  );

}